name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Grading of Task 1.1. - (kmeans) _initialize_partitions
      id: kmeansinitializepartitions
      uses: FAU-CS6-KDDmUe-Submissions/Custom-Python-Autograder@v1
      with:
        timeout: '15'
        max-score: '3'
        setup-command: 'pip install -r requirements.txt'
        test-path: 'tests/kmeans/test_initialize_partitions.py'
    - name: Grading of Task 1.2. - (kmeans) _update_centroids
      id: kmeansupdatecentroids
      uses: FAU-CS6-KDDmUe-Submissions/Custom-Python-Autograder@v1
      with:
        timeout: '15'
        max-score: '3'
        setup-command: 'pip install -r requirements.txt'
        test-path: 'tests/kmeans/test_update_centroids.py'
    - name: Grading of Task 1.3. - (kmeans) _reassign_points
      id: kmeansreassignpoints
      uses: FAU-CS6-KDDmUe-Submissions/Custom-Python-Autograder@v1
      with:
        timeout: '15'
        max-score: '5'
        setup-command: 'pip install -r requirements.txt'
        test-path: 'tests/kmeans/test_reassign_points.py'
    - name: Grading of Task 1.4. - (kmeans) fit
      id: kmeansfit
      uses: FAU-CS6-KDDmUe-Submissions/Custom-Python-Autograder@v1
      with:
        timeout: '15'
        max-score: '3'
        setup-command: 'pip install -r requirements.txt'
        test-path: 'tests/kmeans/test_fit.py'

    - name: Grading of Task 2.1. - (dbscan) _get_neighborhood
      id: dbscangetneighborhood
      uses: FAU-CS6-KDDmUe-Submissions/Custom-Python-Autograder@v1
      with:
        timeout: '15'
        max-score: '2'
        setup-command: 'pip install -r requirements.txt'
        test-path: 'tests/dbscan/test_get_neighborhood.py'
    - name: Grading of Task 2.2. - (dbscan) fit
      id: dbscanfit
      uses: FAU-CS6-KDDmUe-Submissions/Custom-Python-Autograder@v1
      with:
        timeout: '15'
        max-score: '14'
        setup-command: 'pip install -r requirements.txt'
        test-path: 'tests/dbscan/test_fit.py'

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        KMEANSINITIALIZEPARTITIONS_RESULTS: ${{ steps.kmeansinitializepartitions.outputs.result }}
        KMEANSUPDATECENTROIDS_RESULTS: ${{ steps.kmeansupdatecentroids.outputs.result }}
        KMEANSREASSIGNPOINTS_RESULTS: ${{ steps.kmeansreassignpoints.outputs.result }}
        KMEANSFIT_RESULTS: ${{ steps.kmeansfit.outputs.result }}
        DBSCANGETNEIGHBORHOOD_RESULTS: ${{ steps.dbscangetneighborhood.outputs.result }}
        DBSCANFIT_RESULTS: ${{ steps.dbscanfit.outputs.result }}
      with:
        runners: kmeansinitializepartitions,kmeansupdatecentroids,kmeansreassignpoints,kmeansfit,dbscangetneighborhood,dbscanfit